services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - domain-services
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysqldb:/var/lib/mysql

  config-server:
    build:
      context: .
      dockerfile: ./config-server/Dockerfile
    container_name: config-server
    ports:
      - "${CONFIG_SERVER_PORT}:8888"
    environment:
      - CONFIG_SERVER_PORT=${CONFIG_SERVER_PORT}
    networks:
      - domain-services
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://config-server:${CONFIG_SERVER_PORT}/actuator/health" ]
      interval: 20s
      timeout: 3s
      retries: 5
    restart: on-failure

  discovery-service:
    build:
      context: .
      dockerfile: ./discovery-service/Dockerfile
    container_name: discovery-service
    depends_on:
      config-server:
        condition: service_healthy
    ports:
      - "${EUREKA_SERVER_PORT}:8761"
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:${CONFIG_SERVER_PORT}
      - EUREKA_SERVER_PORT=${EUREKA_SERVER_PORT}
    networks:
      - domain-services
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://discovery-service:${EUREKA_SERVER_PORT}/actuator/health" ]
      interval: 20s
      timeout: 3s
      retries: 5
    restart: on-failure

  user-service:
    build:
      context: .
      dockerfile: ./domain-services/user-service/Dockerfile
    container_name: user-service
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      mysqldb:
        condition: service_started
    ports:
      - "${USER_SERVICE_PORT}:8082"
    environment:
      - USER_SERVER_PORT=${USER_SERVICE_PORT}
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:${CONFIG_SERVER_PORT}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:${EUREKA_SERVER_PORT}/eureka/
      - SPRING_MYSQL_URI=jdbc:mysql://mysqldb:${MYSQL_PORT}/${USER_DB_NAME}?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - domain-services

  post-service:
    build:
      context: .
      dockerfile: ./domain-services/post-service/Dockerfile
    container_name: post-service
    depends_on:
      config-server:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      mysqldb:
        condition: service_started
    ports:
      - "${POST_SERVICE_PORT}:8081"
    environment:
      - POST_SERVER_PORT=${POST_SERVICE_PORT}
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:${CONFIG_SERVER_PORT}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:${EUREKA_SERVER_PORT}/eureka/
      - SPRING_MYSQL_URI=jdbc:mysql://mysqldb:${MYSQL_PORT}/${POST_DB_NAME}?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - domain-services

volumes:
  mysqldb:
networks:
  domain-services:
    driver: bridge